#!/bin/bash

usage() {
  echo -e "Usage: $0 [options...] <path_to_script> \n\
 -h, --help          Display help
 -o, --output <path> Output path where to save results \n\
 -f, --format        Specifies the format of the command's output. [pretty|sparse|prettyjson|json|csv] (default=pretty). \n\
 -n, --max           The number of rows to return in the query results. (default=100). \n\
 -V, --verbose       Make the operation more talkative" 1>&2
  exit 1
}

output=""
verbose=0
max=100
format="pretty"

while [[ $# -gt 0 ]]; do
  case $1 in
  -h | --help)
    usage
    shift
    ;;
  -V | --verbose)
    verbose=1
    shift
    ;;
  -n | --max)
    max=$2
    shift 2
    ;;
  -f | --format)
    format=$2
    shift 2
    ;;
  -o | --output)
    output=$2
    shift 2
    ;;
  *)
    script=$1
    shift
    break
    ;;
  esac
done

login=$(gcloud config get account)

if [ -z "$login" ]; then
  echo "Not logged in. Please login with 'gcloud auth login'"
  exit 1
fi

project=$(gcloud config get project)

if [ -z "$project" ]; then
  echo "No project set. Please set a project using 'gcloud config set project <PROJECT_ID>'"
  exit 1
fi

echo -e "Using project: $project"

if [ -z "$script" ]; then
  usage
fi

sql=$(<$script)

if [ "$verbose" == 1 ]; then
  echo -e "Running bq query on $script"
  echo -e "...\n"
fi

if [ -f "$output" ]; then
  read -p "Output file exists. Overwrite? (y/N) " -n 1 -r
  echo
  if [[ $REPLY =~ ^[Nn]$ ]] || [[ -z $REPLY ]]; then
    exit
  fi
  > $output
fi

if [ -z "script" ]; then
  if [ ! -f "$output" ]; then
    touch $output
  fi
fi

if [ ! -z "$output" ]; then
  if [ "$verbose" == 1 ]; then
    echo "Overwriting contents in $output"
    echo
  fi
fi

if [ "$verbose" == 1 ]; then
  echo -e "bq query --use_legacy_sql=false --format=$format \n\"$sql\""
  echo
fi

bq query --max_rows=$max --use_legacy_sql=false --format=$format "$sql" |
  if [ ! -z "$output" ]; then
    tee 1>>$output 2>&1
  else
    cat
  fi

if [ ! -z "$output" ] && [ "$verbose" == 1 ]; then
  echo -e "Saved results to $output\n"
fi

if [ "$verbose" == 1 ]; then
  echo "Done."
fi
